# Generated by Django 3.2 on 2021-04-19 15:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0002_order_orderitem_reviews_shippingaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
        migrations.RenameModel(
            old_name='ShippingAddress',
            new_name='ShippingAddres',
        ),
    ]
