# Generated by Django 3.2 on 2021-07-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_product_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
        migrations.AddField(
            model_name='product',
            name='qtty',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
